#ifndef SENSORS_h_
#define SENSORS_h_

#include "hci.h"

#define TENC_ENG_SPEED_GAIN 60.0
#define TENC_SNS_P_DIFF_DPF_BIAS -44.35 //-45.386
#define TENC_SNS_P_DIFF_DPF_GAIN 86.96 //91.084
#define TENC_SNS_MANIFOLD_P_BIAS 0.0
#define TENC_SNS_MANIFOLD_P_GAIN 100.0

#define HUASDER_THERMOCOUPLE 0
#define K_TYPE_THERMOCOUPLE 1
#define TEMPERATURE_OVERRIDE_VALUE -273.0
#define CAN_FF09_MAX_ERROR_COUNT 5 // 500 ms

#define TENC_SNS_MANIFOLD_PRESSURE_MINIMUM_VAL 0.05
#define TENC_SNS_MANIFOLD_PRESSURE_MAXIMUM_VAL 4.8

#define TENC_SNS_P_DIFF_DPF_MINIMUM_VAL 0.05
#define TENC_SNS_P_DIFF_DPF_MAXIMUM_VAL 4.8

void get_sensors_value(void);
#endif
